export default new_data = [
  {
	"id": "29",
    "date": "March 29",
    "time": "8:26pm",
    "score": "90",
    "image": "./images/up_arrow.png",
    "exercise": false,
    "medication": true,
    "sleep": true,
    "improvement": true
  },
  {
	"id": "28",
    "date": "March 28",
    "time": "5:13am",
    "score": "86",
    "exercise": true,
    "medication": false,
    "sleep": true,
    "improvement": true,
  },
  {
	"id": "27",
    "date": "March 27",
    "time": "12:12pm",
    "score": "73",
    "exercise": true,
    "medication": false,
    "sleep": false,
    "improvement": true
  },
  {
	"id": "26",
    "date": "March 26",
    "time": "8:26pm",
    "score": "61",
    "image": "./images/up_arrow.png",
    "exercise": false,
    "medication": true,
    "sleep": true,
    "improvement": true
  },
  {
	"id": "25",
    "date": "March 25",
    "time": "5:13am",
    "score": "55",
    "exercise": false,
    "medication": false,
    "sleep": true,
    "improvement": true,
  },
  {
	"id": "24",
    "date": "March 24",
    "time": "12:12pm",
    "score": "47",
    "exercise": true,
    "medication": false,
    "sleep": false,
    "improvement": true
  },
  {
	"id": "23",
    "date": "March 23",
    "time": "12:12pm",
    "score": "46",
    "exercise": true,
    "medication": true,
    "sleep": true,
    "improvement": false
  },
  {
	"id": "22",
    "date": "March 22",
    "time": "8:26pm",
    "score": "50",
    "image": "./images/up_arrow.png",
    "exercise": false,
    "medication": true,
    "sleep": true,
    "improvement": false
  },
  {
	"id": "21",
    "date": "March 21",
    "time": "5:13am",
    "score": "55",
    "exercise": true,
    "medication": false,
    "sleep": true,
    "improvement": true,
  },
  {
	"id": "20",
    "date": "March 20",
    "time": "12:12pm",
    "score": "37",
    "exercise": true,
    "medication": false,
    "sleep": false,
    "improvement": true
  },
  {
	"id": "19",
    "date": "March 19",
    "time": "8:26pm",
    "score": "28",
    "image": "./images/up_arrow.png",
    "exercise": false,
    "medication": true,
    "sleep": true,
    "improvement": true
  },
  {
	"id": "18",
    "date": "March 18",
    "time": "5:13am",
    "score": "27",
    "exercise": false,
    "medication": false,
    "sleep": true,
    "improvement": true,
  },
  {
	"id": "17",
    "date": "March 17",
    "time": "12:12pm",
    "score": "25",
    "exercise": true,
    "medication": false,
    "sleep": false,
    "improvement": true
  },
  {
	"id": "16",
    "date": "March 16",
    "time": "12:12pm",
    "score": "20",
    "exercise": true,
    "medication": true,
    "sleep": true,
    "improvement": false
  },
  {
	"id": "15",
    "date": "March 15",
    "time": "8:26pm",
    "score": "39",
    "image": "./images/up_arrow.png",
    "exercise": false,
    "medication": true,
    "sleep": true,
    "improvement": false
  },
  {
	"id": "14",
    "date": "March 14",
    "time": "5:13am",
    "score": "42",
    "exercise": true,
    "medication": false,
    "sleep": true,
    "improvement": false,
  },
  {
	"id": "13",
    "date": "March 13",
    "time": "12:12pm",
    "score": "50",
    "exercise": true,
    "medication": false,
    "sleep": false,
    "improvement": true
  },
  {
	"id": "12",
    "date": "March 12",
    "time": "8:26pm",
    "score": "44",
    "image": "./images/up_arrow.png",
    "exercise": false,
    "medication": true,
    "sleep": true,
    "improvement": true
  },
  {
	"id": "11",
    "date": "March 11",
    "time": "5:13am",
    "score": "40",
    "exercise": false,
    "medication": false,
    "sleep": true,
    "improvement": true,
  },
  {
	"id": "10",
    "date": "March 10",
    "time": "12:12pm",
    "score": "32",
    "exercise": true,
    "medication": false,
    "sleep": false,
    "improvement": false
  },
  {
	"id": "9",
    "date": "March 9",
    "time": "12:12pm",
    "score": "37",
    "exercise": true,
    "medication": true,
    "sleep": true,
    "improvement": true
  },
  {
	"id": "8",
    "date": "March 8",
    "time": "8:26pm",
    "score": "29",
    "image": "./images/up_arrow.png",
    "exercise": false,
    "medication": true,
    "sleep": true,
    "improvement": true
  },
  {
	"id": "7",
    "date": "March 7",
    "time": "5:13am",
    "score": "25",
    "exercise": true,
    "medication": false,
    "sleep": true,
    "improvement": false,
  },
  {
	"id": "6",
    "date": "March 6",
    "time": "12:12pm",
    "score": "26",
    "exercise": true,
    "medication": false,
    "sleep": false,
    "improvement": true
  },
  {
	"id": "5",
    "date": "March 5",
    "time": "8:26pm",
    "score": "19",
    "image": "./images/up_arrow.png",
    "exercise": false,
    "medication": true,
    "sleep": true,
    "improvement": false
  },
  {
	"id": "4",
    "date": "March 4",
    "time": "5:13am",
    "score": "20",
    "exercise": false,
    "medication": false,
    "sleep": true,
    "improvement": true,
  },
  {
	"id": "3",
    "date": "March 3",
    "time": "12:12pm",
    "score": "14",
    "exercise": true,
    "medication": false,
    "sleep": false,
    "improvement": false
  },
  {
	"id": "2",
    "date": "March 2",
    "time": "12:12pm",
    "score": "16",
    "exercise": true,
    "medication": true,
    "sleep": true,
    "improvement": true
  },
  {
	"id": "1",
    "date": "March 1",
    "time": "12:12pm",
    "score": "15",
    "exercise": false,
    "medication": true,
    "sleep": true,
    "improvement": true
  },
  {
	"id": "1",
    "date": "April 30",
    "time": "12:12pm",
    "score": "13",
    "exercise": true,
    "medication": true,
    "sleep": false,
    "improvement": true
  }
];